### PR TITLE
Whoops. 2 "Sanctuary" cards were still bugged.

### PR DESCRIPTION
**Pull request by senpaizuri3**

### CODE REVIEW

**Comment by EerieCode** [comment]
You sure you wanna keep that pull name? That's also shown on Ygopro, you know! XD

**Comment by senpaizuri3** [comment]
Actually the only stuff that shows on YGOPro's update log are the commit names, not the PR names. (I discovered this with only getting "Added files via upload" credits. XP)

**Comment by EerieCode** [comment]
Ok then!

**Comment by Steeldarkeagel** [comment]
A little bit of professionalism would be good though. Thanks

**Pull request merged**
