### PR TITLE
Added new cards

### PR DESCRIPTION
**Pull request by EerieCode**

### CODE REVIEW

**Comment by kenpazaraki** [comment]
Subterror Final battle is bugged:
29: attempt to index global 'ops' (a nil value)

**Comment by EerieCode** [comment]
...ops? ;P

**Comment by kenpazaraki** [comment]
Fiendess is still bugged, also Speleogeist can target monster in attack position with its effect.

**Comment by EerieCode** [comment]
_You can target 1 monster on the field; change it to face-up Attack Position **if it is in Defense Position**, also change its ATK to 0._

Doesn't the bolded part imply that monsters not in Defense position can in fact be targeted (in which case, only the ATK reduction would apply)?

**Comment by Steeldarkeagel** [comment]
Look at the commas Eerie.
First statement: change it to face-up Attack Position if it is in Defense Position
Second statement: also change its ATK to 0
If the comma was after Attack Position it would be
First statement: change it to face-up Attack Position 
Second statement:  if it is in Defense Position also change its ATK to 0

**Comment by Steeldarkeagel** [comment]
^ Correct

**Comment by kenpazaraki** [comment]
Oops, missed that :)

**Pull request merged**
