### PR TITLE
Added "Digitron"

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by EerieCode** [comment]
For crying out loud, I already said I'll upload them later!

**Comment by marikisthar** [comment]
sorry, i just want to help

**Comment by EerieCode** [comment]
I get that, but if we start editing the databases on different pulls we risk a conflict later on. It's best if the same person adds the cards, this way things will go smoother.

**Comment by marikisthar** [comment]
ok, i get it


 btw did you know how to delete pull requests??

**Comment by EerieCode** [comment]
You should see a button "Close pull request" below, it should be enough.

**Pull request closed without merging**
