### PR TITLE
Fix missing cards OTs

### PR DESCRIPTION
**Pull request by ghost**
Fixed OT for missing EP17 Cards:
-  SPYRal resort
- The Hiddecn City
- Charming Resort Staff

misplaced

### CODE REVIEW

**Comment by marikisthar** [comment]
still no response???

**Comment by shadowfox87** [comment]
Your pull has conflicts. Only fixot.cdb should have been changed for ot changes yet you changed fixstr.cdb.

**Comment by marikisthar** [comment]
spyral resort is on fixstr,cdb

should i  rewrite it on fixot.cdb???

**Comment by shadowfox87** [comment]
Just redo the pull request. I am closing it since it has conflicts.

**Pull request closed without merging**
