### PR TITLE
Added Missing constants

### PR DESCRIPTION
**Pull request by TheOnePharaoh**

### CODE REVIEW

**Comment by EerieCode** [comment]
I can't find any of these constants on Fluoro's constant.lua. Are you sure these are official?

**Comment by edo9300** [comment]
@EerieCode those are my effects

**Comment by edo9300** [comment]
And if you can, rename always attack to unstopable attack, it woukd be better XD

**Review by edo9300 — CHANGES_REQUESTED** [review]
a

**Pull request closed without merging**
