### PR TITLE
New cards and bug fixes

### PR DESCRIPTION
**Pull request by EerieCode**

### CODE REVIEW

**Comment by EerieCode** [comment]
@TharmB For the record, next time you want to edit a setcode, use fixsetcode. Don't copy the whole cards.cdb in Live: aside from taking up a ton of space, it causes all kinds of issues with the other databases,

**Comment by TharmB** [comment]
Ah, my mistake, will do that in future! Very sorry about that!

**Comment by Sun4Ever2** [comment]
you're going to upload also the new banlist in this batch right

**Comment by EerieCode** [comment]
No. The banlists are updated the day they actually start being used.

**Comment by kenpazaraki** [comment]
I found a few bugs:
- Metaphys Ragnarok's Battle Phase effect doesn't activate
- Metaphys Tyrant Dragon summons from the Deck and not from the hand
image

**Comment by EerieCode** [comment]
I should have fixed all of them. Thanks!

**Pull request merged**
